# Generated by Django 4.1.7 on 2023-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
